name: Search Code in GitHub Repository

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Name of the repository'
        required: true
      search_query:
        description: 'Code to search for'
        required: true

jobs:
  search-code:
    runs-on: ubuntu-latest
    steps:
      - name: Search Code
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.graphql(`
              query ($repo: String!, $searchQuery: String!) {
                repository(name: $repo) {
                  object(expression: "main") {
                    ... on Commit {
                      history(path: $searchQuery, first: 10) {
                        nodes {
                          oid
                          message
                        }
                      }
                    }
                  }
                }
              }
            `, {
              repo: ${{ github.event.inputs.repository }},
              searchQuery: ${{ github.event.inputs.search_query }}
            });
            console.log(response);
