name: Search GitHub Repository

on:
  workflow_dispatch:

jobs:
  search-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Search Code
        uses: graphql-github-v4@v1
        with:
          query: |
            query SearchCode($owner: String!, $repo: String!, $searchString: String!) {
              repository(owner: $owner, name: $repo) {
                object(expression: "master") {
                  ... on Commit {
                    history(first: 100) {
                      nodes {
                        oid
                      }
                    }
                  }
                }
                search(query: $searchString, type: CODE, first: 10) {
                  edges {
                    node {
                      ... on SearchCode {
                        path
                        repository {
                          nameWithOwner
                        }
                      }
                    }
                  }
                }
              }
            }
          variables: |
            {
              "owner": "medhekars",
              "repo": "testGithubSearch",
              "searchString": "log-forwarder-version"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
