name: Search Code in Organization Repositories

on:
  workflow_dispatch:

jobs:
  search_code:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @actions/core @actions/http-client

      - name: Browse organization repositories
        id: browse_repos
        run: |
          echo "REPO_LIST=['testGithubSearch']" >> GITHUB_ENV
          
      - name: Search code in repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_LIST: ${{ env.REPO_LIST }}
        run: |
          const core = require('@actions/core');
          const { HttpClient } = require('@actions/http-client');

          const token = process.env.GITHUB_TOKEN;
          const repoList = JSON.parse(process.env.REPO_LIST);
          const searchQuery = "forwarder";

          for (const repo of repoList) {
            const httpClient = new HttpClient('search-code-action')
            const response = await httpClient.get(
              `https://api.github.com/search/code?q=${encodeURIComponent(searchQuery)}+repo:${repo}`,
              {
                headers: {
                  "Authorization: Bearer ${{ secrets.PAT_GITHUB_TOKEN }}",
                  'User-Agent': 'search-code-action'
                }
              }
            )
           }
            
            const responseBody = await response.readBody();
            const searchResults = JSON.parse(responseBody);
            console.log(`Search results in ${repo}:`, searchResults);
