name: Search Code in GitHub Repository

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of the repository'
        required: true
      repository:
        description: 'Name of the repository'
        required: true
      search_query:
        description: 'Code to search for'
        required: true

jobs:
  search-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Search Code
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.PAT_GITHUB_TOKEN }}" -d '{
            "query": "query { search(query: \"repo:$owner/$repository $search_query\", type: CODE, first: 10) { nodes { ... on SearchItem { ... on Code { name path } } } } }"
          }' https://api.github.com/graphql
        env:
          owner: ${{ github.event.inputs.owner }}
          repository: ${{ github.event.inputs.repository }}
          search_query: ${{ github.event.inputs.search_query }}
